- name: Create users and groups
  hosts: all
  become: true
  vars:
    users:
      - name: user100
      - name: user200
      - name: user300
    groups:
      - name: cloudadmins
  tasks:
    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ groups }}"
    - name: Create users
      user:
        name: "{{ item.name }}"
        groups: "cloudadmins,wheel"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
        ssh_key_type: rsa
      loop: "{{ users }}"
    - name: Distribute SSH keys
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      loop: "{{ users }}"